In [4]:
import numpy as np


t1 = 0
t2 = 0
t3 = -np.pi / 2
t4 = np.pi / 2
theta = [t1, t2, t3, t4]

a = [0, 0, 0, 44.725, 35, 0, 144.725, 135, 0, 144.725]
rot = [[0, 0, 1, 0], [1, 0, 0, 0], [1, 0, 0, 1, 0]]

jt = "RRRR"

M = np.array([[1, 0, 0, 142.6],
              [0, 1, 0, 0],
              [0, 0, 1, 244.725],
              [0, 0, 0, 1]])

def Pose(theta, a, rot, jt, M):
    R = M[:3, :3]
    p = M[:3, 3]
    return R, p

R, p = Pose(theta, a, rot, jt, M)
print("R =")
print(R)
print("\np =")
print(p)


R =
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

p =
[142.6     0.    244.725]
