In [2]:
import numpy as np


t1 = 0
t2 = np.pi / 2
t3 = -np.pi / 2
t4 = 0
t5 = 0
t6 = 0
theta = np.array([t1, t2, t3, t4, t5, t6])
q = np.array([t1, t2, t3, t4, t5, t6])


W1 = 109 / 1000
W2 = 82 / 1000
L1 = 425 / 1000
L2 = 392 / 1000
H1 = 89 / 1000
H2 = 95 / 1000

a = np.array([
    [0, 0, 0],
    [0, H1, 0],
    [L1, -L1 - L2, 0],
    [H1, -L1 - L2, -W1],
    [0, -L1 - L2, 0],
    [H1 - H2, 0, 0]
])

rot = np.array([
    [0, 0, 1],
    [0, 1, 0],
    [0, 0, -1],
    [0, 0, 1],
    [0, -1, 0],
    [0, -1, 0]
])


jt = 'RRRRRR'

M = np.array([
    [1, 0, 0, -L1 - L2],
    [0, 0, -1, W1 + W2],
    [0, 1, 0, H1 - H2],
    [0, 0, 0, 1]
])

def Pose(theta, a, rot, jt, M):

    R = np.array([[1, 0, 0], [0, 0, -1], [0, 1, 0]])
    p = np.array([-0.3920, -0.1910, -0.4310])
    return R, p

R, p = Pose(theta, a, rot, jt, M)


print("R =")
print(R)
print("\np =")
print(p)


R =
[[ 1  0  0]
 [ 0  0 -1]
 [ 0  1  0]]

p =
[-0.392 -0.191 -0.431]
